server:
  port: 8080

amadeus:
  api:
    client-id: ${AMADEUS_API_KEY}
    client-secret: ${AMADEUS_API_SECRET}
    token-url: https://test.api.amadeus.com/v1/security/oauth2/token
    flight-search-url: https://test.api.amadeus.com/v2/shopping/flight-offers
    airlines-url: https://test.api.amadeus.com/v1/reference-data/airlines
    airports-url: https://test.api.amadeus.com/v1/reference-data/locations
